<?php

$helper = Mage::helper('sheerid_verify');

$defaultTemplateId = $helper->getDefaultCampaignId();
if ($defaultTemplateId && !$this->getTemplateId()) {
	$this->setTemplateId($defaultTemplateId);
}

if ($this->getTemplateId()) { ?>
	<iframe id="sheerid-iframe" src="<?php echo $helper->getVerifyUrl($this->getTemplateId()); ?>"></iframe>
<?php } else { ?>
	<h3>SheerID: Campaign Not Found</h3>
<?php }