<style type="text/css">
.block-verify .block-content {
	padding: 6px;
}
.block-verify .input-box {
	width: 100% !important;
}
.block-verify .form-list li.wide select, .block-verify .form-list li.wide input {
	width: 95%;
}
</style>
<div class="block block-verify">
	<div class="block-title">
		<strong><span><?php echo $this->getTitle(); ?></span></strong>
	</div>
	<div class="block-content">
		<div id="verify-form">
			<p><?php echo $this->getDescription(); ?></p>
			<p><a href="javascript:sheerIdVerify();"><?php echo Mage::helper('sheerid_verify')->__("Click here to verify"); ?></a></p>
		</div>
	</div>
</div>
<?php $this->widgetJavaScript(); ?>
