<style type="text/css">
.block-verify .block-content {
	padding: 6px;
}
</style>
<div class="block block-verify">
	<div class="block-title">
		<strong><span><?php echo $this->getTitle(); ?></span></strong>
	</div>
	<div class="block-content">
		<div id="verify-form">
			<p><?php echo $this->getDescription(); ?></p>
			<p><a href="#" data-sheerid-campaign="<?php echo $this->getTemplateId(); ?>"><?php echo Mage::helper('sheerid_verify')->__("Click here to verify"); ?></a></p>
		</div>
	</div>
</div>
