<?php
	$helper = Mage::helper('sheerid_verify');

	$block = $this->getLayout()->createBlock('sheerid/verify', 'SheerID_Verify');

	if ('cookie' == $helper->getSetting("show_in_checkout")) {
		$block->setAffiliationTypes($_COOKIE[$helper->getSetting("show_in_checkout_cookie_name")]);
	} else {
		$block->setAffiliationTypes($helper->getSetting("show_in_checkout_affiliation_types"));
	}

	$block->setSubmit(false);
	$block->setUseAjax(false);
	$block->setUseQuoteInformation(true);
	
	echo $block->toHtml();
?>
<div class="buttons-set" id="verify-buttons-container">
    <p class="required"><?php echo $this->__('* Required Fields') ?></p>
	<p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>« </small><?php echo $this->__('Back') ?></a></p>
	<button type="button" class="button" onclick="sheerid_verify.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
	<a href="javascript:sheerid_verify.skip();" id="verify-skip" class="f-right"><small>Skip this step</small></a>
	<span class="please-wait" id="verify-please-wait" style="display: none;">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
	</span>
</div>

<script src="https://www.sheerid.com/jsapi/js/SheerID.js"></script>
<script type="text/javascript">
//<![CDATA[

var SheerIDVerify = Class.create();
SheerIDVerify.prototype = {
    initialize: function(form, saveUrl){
        this.form = form;
        if ($(this.form)) {
            $(this.form).observe('submit', function(event){this.save();Event.stop(event);}.bind(this));
        }
        this.saveUrl = saveUrl;
        this.onSave = this.nextStep.bindAsEventListener(this);
        this.onComplete = this.resetLoadWaiting.bindAsEventListener(this);
    },

    save: function(){
        if (checkout.loadWaiting!=false) return;
		
		$$('.verify-messages').each(function(i){ i.remove() });

        var validator = new Validation(this.form, {onFormValidate:function(form){
			var dob_failure = $$('#verify_birth_date select.validation-failed').length > 0;

			var advice = $('advice-verify_birth_date');			
			if (advice && dob_failure) {
				new Effect.Appear(advice, {duration : 1 });
			} else if (advice) {
				new Effect.Fade(advice, {duration : 1 });
			}
		}});
        if (validator.validate()) {

            checkout.setLoadWaiting('verify');

            var request = new Ajax.Request(
                this.saveUrl,
                {
                    method: 'post',
                    onComplete: this.onComplete,
                    onSuccess: this.onSave,
                    onFailure: checkout.ajaxFailure.bind(checkout),
                    parameters: Form.serialize(this.form)
                }
            );
        }
    },

    resetLoadWaiting: function(transport){
        checkout.setLoadWaiting(false);
    },

    nextStep: function(transport){
        if (transport && transport.responseText){
            try{
                response = eval('(' + transport.responseText + ')');
            }
            catch (e) {
                response = {};
            }
        }

        if (response.error){
			var msgs;
            if ((typeof response.message) == 'string') {
                msgs = [response.message];
            } else {
				msgs = response.message;
				if (window.billingRegionUpdater) {
					billingRegionUpdater.update();
				}
            }

			<?php if (Mage::getStoreConfig('sheerid_options/settings/allow_uploads') == "1") { ?>
			msgs.push('<a href="javascript:sheerid_verify.upload()"><?php echo Mage::helper('sheerid_verify')->__("Upload proof of affiliation"); ?></a>');
			<?php } ?>

			$('co-verify-form').insert({before:'<p class="verify-messages error">'+msgs.join('<br/>')+'</p>'});
			
			new Effect.Appear($('verify-skip'), {duration : 1 });

            return false;
        }

        checkout.setStepResponse(response);
    },

    upload : function() {
		var that = this;
		
        checkout.setLoadWaiting('verify');
		$('checkout-step-verify').insert({'top':'<div id="checkout-step-verify-upload"></div>'});

		var request = new Ajax.Request(
            '/checkout/onepage/verifyUploadToken',
            {
                method: 'post',
                onComplete: this.resetLoadWaiting.bindAsEventListener(this),
                onSuccess: function(transport) {
					if (transport && transport.responseText){
						var response;
						try{
							response = eval('(' + transport.responseText + ')');
						} catch (e) {
							response = {};
						}
						if (response.token) {
							SheerID.load('asset', '1.0', {
								config: {
									container : 'checkout-step-verify-upload',
									maxFiles: 3,
									baseUrl : response.baseUrl,
									success : '<?php echo Mage::app()->getStore()->getBaseUrl();?>checkout/onepage/verifyUploadSuccess',
									failure : '<?php echo Mage::app()->getStore()->getBaseUrl();?>checkout/onepage/verifyUploadFailure',
									onSuccess : function() {
										that.skip();
									},
									ajax: true,
									token: response.token
								}
							});
							$$('.verify-messages').each(function(i){ i.remove() });
							$('verify-buttons-container').hide();
							$('co-verify-form').hide();
							$('checkout-step-verify').insert('<p><a href="javascript:sheerid_verify.skip();" id="verify-skip"><small><?php echo Mage::helper('sheerid_verify')->__("Skip this step"); ?></small></a></p>');
						}
			        } else {
						checkout.ajaxFailure(transport);
					}
				},
                onFailure: checkout.ajaxFailure.bind(checkout),
                parameters: {}
            }
        );
	},

	skip : function() {
		try {
			checkout.setStepResponse({goto_section:'shipping_method'});
		} catch (e) {
			checkout.setStepResponse({goto_section:'payment'});
		}
	}
}

sheerid_verify = new SheerIDVerify('co-verify-form', '<?php echo $this->getUrl('checkout/onepage/saveVerify') ?>');

//]]>
</script>
