<script type="text/javascript" src="https://www.sheerid.com/jsapi/js/SheerID.js"></script>
<script type="text/javascript">
addSheerIDEventListeners = function() {
	$$('form.verify-form-ajax').each(function(el) {
		Event.observe(el, 'submit', function(event) {
			var validator = typeof Validation == 'function' ? new Validation(el) : (function(){return{validate:function(){return true;}}}());
			if (validator.validate()) {
				$$('.verify-messages')[0].update('');
				var loader = $('verify-please-wait');
				loader.show();
				this.request({
					evalJSON : 'force',
					parameters: {
						'ajax' : true
					},
			        onFailure: function() {
						loader.hide();
					},
			        onSuccess: function(t) {
						loader.hide();
			            var resp = t.responseJSON;
						if (resp.result) {
							$$('.verify-messages')[0].removeClassName('error').update(resp.message || 'Success!');
							el.hide();
						} else {
							$$('.verify-messages')[0].addClassName('error').update(resp.errors.join('<br/>'))
						}
					
						if (resp.refresh) {
							window.location.reload();
						}
			        }
				});
			}
		    Event.stop(event);
		});
	});
	
	SheerIDOrganizationFields = $$('.sheerid-orgs');
	if (SheerIDOrganizationFields.length) {
		if (SheerIDOrganizationFields.length == 1) {
			var type = null;
			var m = SheerIDOrganizationFields[0].className.match(/sheerid-orgs-(\w+)/);
			if (m) {
				type = m[1];
			}
			SheerID.load('combobox', '1.0', {
				baseUrl: 'https://sheerid.local/jsapi',
				config: {
					baseUrl: 'https://sheerid.local',
					allowName: true,
					input: SheerIDOrganizationFields[0],
					params: {
						type: type ? type : 'university'
					}
				}
			});
		}
	}
}
addSheerIDEventListeners();
</script>
