<?php

$helper = Mage::helper('sheerid_verify');

$MONTHS = array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');

// defaults
if ($this->getCollectName() !== false) {
	$this->setCollectName(true);
}
if ($this->getUseAjax() !== false) {
	$this->setUseAjax(true);
}

$prompt = $this->getPrompt();

if ($this->getFields()) {
  $fields = explode(",", $this->getFields());
} else {
  $fields = $helper->getFields($this->getAffiliationTypes(), $this->getOrganizationId());
}

if ($this->getUseQuoteInformation()) {
  $fields = array_diff($fields, array("FIRST_NAME", "LAST_NAME", "POSTAL_CODE", "EMAIL"));
}

$orgType = $helper->getOrganizationType(explode(',', $this->getAffiliationTypes()));
$organization_label = $helper->getOrganizationLabel($orgType);

$affiliation_types = explode(',', $this->getAffiliationTypes());

// require that a choice be possible before enforcing that user makes one
if (count($affiliation_types) < 2) {
  $this->setChooseAffiliationType(false);
}

?>

<?php if (!$this->getFormOnly()) {?>
<div id="sheerid_verify">
	<p class="verify-prompt"><?php echo $prompt ? $prompt : $this->__('Please supply the following information so we can verify your affiliation.'); ?></p>
	<p class="verify-messages"></p>
	<?php if ($this->getChooseAffiliationType()) { ?>
		<div class="verify-status">
			<p>
				<label><strong><?php echo $this->__('Select your status:'); ?></strong></label>
				<select class="affiliation-type-choice">
					<option value=""><?php echo $this->__('Select one...'); ?></option>
				<?php foreach ($affiliation_types as $type) { ?>
					<option value="<?php echo $type ?>"><?php echo $this->__($type) ?></option>
				<?php } ?>
				</select>
			</p>
		</div>
	<?php } ?>
	<form id="co-verify-form" class="verify-form <?php echo $this->getUseAjax()?"verify-form-ajax":"";?>" action="<?php echo Mage::getUrl('SheerID/verify/verify'); ?>" method="POST">
<?php } ?>
<?php if (!$this->getChooseAffiliationType()) { ?>
		<fieldset>
		<ul class="form-list" style="list-style: none; padding-left: 0;">

		<?php if ($this->getOrganizationId()) { ?>
			<input type="hidden" name="verify[organizationId]" value="<?php echo $this->getOrganizationId(); ?>" />
		<?php } else { ?>
		<li class="wide">
			<label for="verify:organizationId" class="required"><em>*</em><?php echo $this->__($organization_label) ?></label>
			<div class="input-box">
				<input type="text" title="<?php echo $this->__($organization_label) ?>" name="verify[organizationId]" id="verify:organizationId" value="" class="input-text required-entry local-validation sheerid-orgs sheerid-orgs-<?php echo strtolower($orgType); ?>"/>
			</div>
		</li>
		<?php } ?>

		<?php foreach ($fields as $f) {
			$name = $f;
			$label = $helper->getFieldLabel($f);
			if ("POSTAL_CODE" == $f) {
				$className = "narrow";
			} else {
				$className = "wide";
			}
		?>
			<li class="<?php echo $className; ?>">
				<label for="verify:<?php echo $name; ?>" class="required"><em>*</em><?php echo $this->__($label) ?></label>
				<div class="input-box">
					<?php if (preg_match('/_DATE$/', $f)) { ?>
						<?php if ('STATUS_START_DATE' == $f) {
							$monthVal = date('m');
							$dayVal = date('d');
							$yearVal = date('Y');
						} ?>
						<div id="verify_<?php echo $name; ?>">
							<select id="verify:<?php echo $name; ?>" name="verify[<?php echo $f; ?>.month]" style="width: 60px; margin-right: 0.5em;" class="required-entry local-validation">
								<option value="">--</option>
								<?php for ($i=1; $i<=count($MONTHS); $i++) { $val = $i < 10 ? "0$i" : $i; ?>
									<option value="<?php echo $val; ?>"<?php if ($monthVal == $val) echo " selected";?>><?php echo $MONTHS[$i-1]; ?></option>
								<?php } ?>
							</select>
		
							<select id="verify:<?php echo $name; ?>.day" name="verify[<?php echo $f; ?>.day]" style="width: 45px; margin-right: 0.5em;" class="required-entry local-validation">
								<option value="">--</option>
								<?php
								for ($i=1; $i<=31; $i++) {
									$v = $i;
									if ($v < 10) { $v = "0$i"; }
									echo "\n<option value=\"$v\"".($dayVal == $v?" selected":"").">$i</option>";
								}
								?>
							</select>
		
							<select id="verify:<?php echo $name; ?>.year" name="verify[<?php echo $f; ?>.year]" style="width: 60px; margin-right: 0.5em;" class="required-entry local-validation">
								<option value="">--</option>
								<?php
								$d = date("Y")/1;
								for ($i=0; $i<100; $i++) {
									$v = $d - $i;
									if ($v == $yearVal) {
										echo "\n<option selected>$v</option>";
									} else {
										echo "\n<option>$v</option>";
									}
								}
								?>
							</select>
						</div>
						<div>
							<div id="advice-verify:<?php echo $name; ?>" style="display: none;"></div>
							<div id="advice-verify:<?php echo $name; ?>.day" style="display: none;"></div>
							<div id="advice-verify:<?php echo $name; ?>.year" style="display: none;"></div>
							<div class="validation-advice" id="advice-verify_<?php echo $name; ?>" style="display: none;"><?php echo $this->__("All date fields are required.");?></div>
						</div>
					<?php } else { ?>
						<input type="text" title="<?php echo $this->__($label); ?>" name="verify[<?php echo $name; ?>]" id="verify:<?php echo $name; ?>" value="" class="input-text required-entry local-validation"/>
					<?php } ?>
				</div>
			</li>
		<?php } ?>
		</ul>
		</fieldset>
		<?php if ($this->getAffiliationTypes()) { ?>
			<input type="hidden" name="verify[affiliation_types]" value="<?php echo $this->getAffiliationTypes(); ?>" />
		<?php } ?>
		<?php if ($this->getOnCartPage()) { ?>
			<input type="hidden" name="on_cart_page" value="1" />
		<?php } ?>
		<?php if ($this->getPromoCode()) { ?>
			<input type="hidden" name="promo_code" value="1" />
		<?php } ?>
		<?php if ($this->getSubmit() !== false) { ?>
			<p>
				<button type="submit" class="button verify-submit"><span><span><?php echo $this->__('Submit') ?></span></span></button>
				<span id="verify-please-wait" class="verify-please-wait" style="display: none;">
					<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" alt="<?php echo $this->__("Verifying...");?>" title="<?php echo $this->__("Verifying...");?>" class="v-middle"><?php echo $this->__("Verifying...");?></span>
			</p>
		<?php } ?>
<?php } ?>
<?php if (!$this->getFormOnly()) { ?>
	</form>
</div>
<?php } ?>
