<?php
$helper = Mage::helper('sheerid_verify');
$config = array();
if ($this->getAffiliationTypes()) {
  $config['affiliation_types'] = $this->getAffiliationTypes();
}
if ($this->getOrganizationId()) {
  $config['organization_id'] = $this->getOrganizationId();
}
if ($this->getBlockPrefix()) {
	$prefix = $this->getBlockPrefix() . "_";
} else {
	$prefix = '';
}

?>
<script type="text/javascript">
function sheerIdVerify() {
        var cfg = <?php echo json_encode($config); ?>;
	cfg.in_cart = <?php echo $this->isOnCartPage(); ?>;
	new Ajax.Updater('verify-form', '/SheerID/verify', {
		method: 'get',
		parameters: cfg,
		onComplete: function(e) {
			addSheerIDEventListeners();
		}
	});
}
</script>
<style type="text/css">
.block-verify .block-content {
	padding: 6px;
}
.block-verify .input-box {
	width: 100% !important;
}
.block-verify .form-list li.wide select, .block-verify .form-list li.wide input {
	width: 95%;
}
</style>
<div class="block block-verify">
	<div class="block-title">
		<strong><span><?php echo $this->getTitle(); ?></span></strong>
	</div>
	<div class="block-content">
		<?php $helper->conditionallyRenderBlock("${prefix}sheerid_widget_header"); ?>
		<div id="verify-form">
			<?php $helper->conditionallyRenderBlock("${prefix}sheerid_widget_body", '<p>'.$this->getDescription().'</p>'); ?>
			<p><a href="javascript:sheerIdVerify();"><?php $link = $this->getLinkMarkup(); echo $link ? $link : Mage::helper('sheerid_verify')->__("Click here to verify"); ?></a></p>
		</div>	
		<?php $helper->conditionallyRenderBlock("${prefix}sheerid_widget_footer"); ?>
	</div>
</div>
